### ISSUE TITLE
Can't generate multiple UUID at once

### ISSUE THREAD

**Issue by MartinX3** [leomillon/uuid-generator-plugin#175]
It only creates a single uuid at the cursor.

Also if I place multiple cursors, it only replaces the last one.
Maybe broken with the current IDE (with the new UI)

I would like to be able to replace every placeholder in a file / project with an UUID.

![image](https://user-images.githubusercontent.com/4518092/216829504-6524f053-37ff-4029-b3db-266ce84ef6f4.png)

**Comment by leomillon** [comment]
Hi @MartinX3 this is working "as expected" because of the way you trigger the action.

The "quick fix actions" are related to the "highlighted part" of the template so the `Replace with new random value` action with only be applied to the cursor used to display this menu.

If you want to replace every templated placeholder in the selection, right now I only manage to trigger this action via "Find action" menu where you should find `Replace Random ID Placeholders in Selection` and that should replace every templated placeholder found in your current selection.

As you can see in the [demo on the README](https://github.com/leomillon/uuid-generator-plugin#demo) section "ID placeholders replacement action": https://github.com/leomillon/uuid-generator-plugin/blob/master/screenshots/id_placeholders_replacement.gif

**Comment by MartinX3** [comment]
Thank you.
I only miss now a `Replace Random ID Placeholders in File`

I needed to google where to find the `Find actions` since I use the new UI and the animated gif didn't help me very well.
(Probably a step by step guide with a link to https://www.jetbrains.com/idea/guide/tips/find-actions/ would help)

**Comment by leomillon** [comment]
Many things have changed in the IntelliJ APIs since I've started this project, so I think I'll rewrite everything with the latest APIs and rethink the way I can suggest actions on cursors.
